---
name: Data Hub API - Stable
exclude:
  - paths.'/spaces'.get.parameters.name=includeConnectors
  - paths.'/spaces'.get.parameters.name=contentUpdatedAt
  - paths.'/spaces/{spaceId}/features'.put.parameters.$ref~=^.*AddTags$
  - paths.'/spaces/{spaceId}/features'.put.parameters.$ref~=^.*RemoveTags$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*AddTags$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*RemoveTags$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*IfExists$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*IfNotExists$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*ConflictResolution$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*Transactional$
  - paths.'/spaces/{spaceId}/features'.post.parameters.$ref~=^.*PrefixId$
  - paths.'/spaces/{spaceId}/features'.delete.parameters.$ref~=^.*TagList$
  - paths.'/spaces/{spaceId}/features/{featureId}'.put.parameters.$ref~=^.*AddTags$
  - paths.'/spaces/{spaceId}/features/{featureId}'.put.parameters.$ref~=^.*RemoveTags$
  - paths.'/spaces/{spaceId}/features/{featureId}'.patch.parameters.$ref~=^.*AddTags$
  - paths.'/spaces/{spaceId}/features/{featureId}'.patch.parameters.$ref~=^.*RemoveTags$
  - paths.'/spaces/{spaceId}/bbox'.get.parameters.$ref~=^.*Tweaks$
  - paths.'/spaces/{spaceId}/bbox'.get.parameters.$ref~=^.*TweaksParams$
  - paths.'/spaces/{spaceId}/bbox'.get.parameters.$ref~=^.*TagList$
  - paths.'/spaces/{spaceId}/tile/{type}/{tileId}'.get.parameters.$ref~=^.*TagList$
  - paths.'/spaces/{spaceId}/tile/{type}/{tileId}'.get.parameters.$ref~=^.*Tweaks$
  - paths.'/spaces/{spaceId}/tile/{type}/{tileId}'.get.parameters.$ref~=^.*TweaksParams$
  - paths.'/spaces/{spaceId}/spatial'.get.parameters.$ref~=^.*TagList$
  - paths.'/spaces/{spaceId}/spatial'.post.parameters.$ref~=^.*TagList$
  - paths.'/spaces/{spaceId}/search'.get.parameters.$ref~=^.*TagList$
  - paths.'/spaces/{spaceId}/history'
  - paths.'/spaces/{spaceId}/history/statistics'
  - paths.'/spaces/{spaceId}/count'
  - paths.'/spaces/{spaceId}/iterate'.get.parameters.$ref~=^.*V$
  - components.parameters.AddTags
  - components.parameters.RemoveTags
  - components.parameters.IfExists
  - components.parameters.IfNotExists
  - components.parameters.ConflictResolution
  - components.parameters.NextPageToken
  - components.parameters.V
  - components.parameters.VStart
  - components.parameters.VEnd
  - components.parameters.Tweaks
  - components.parameters.TweaksParams
  - components.parameters.PrefixId
  - components.parameters.Transactional
  - components.parameters.TagList
  - components.responses.CountFeaturesResponse
  - components.responses.HistoryResponse
  - components.responses.TileResponse.content.'application/vnd.mapbox-vector-tile'
  - components.requestBodies.FeatureCollectionOrFeatureModificationListRequest.content.'application/vnd.here.feature-modification-list'
  - components.schemas.CacheProfile
  - components.schemas.CountResponse
  - components.schemas.Space.properties.enableUUID
  - components.schemas.Space.properties.enableHistory
  - components.schemas.Space.properties.maxVersionCount
  - components.schemas.Space.properties.tags
  - components.schemas.Space.properties.cacheTTL
  - components.schemas.Space.properties.volatilityAtLastContentUpdate
  - components.schemas.Space.properties.volatility
  - components.schemas.Space.properties.autoCacheProfile
  - components.schemas.Space.properties.listeners
  - components.schemas.Space.properties.processors
  - components.schemas.Space.properties.storage
  - components.schemas.Space.properties.client
  - components.schemas.SpaceClient
  - components.schemas.SpaceStorage
  - components.schemas.SpaceStorageParams
  - components.schemas.Changeset
  - components.schemas.ChangesetCollectionResponse
  - components.schemas.CompactChangesetResponse
  - components.schemas.FeatureModificationList
  - components.schemas.FeatureModification
  - components.schemas.OnFeatureNotExists
  - components.schemas.OnFeatureExists
  - components.schemas.OnMergeConflict
  - components.schemas.Connector
replace:
  - type: value
    find: info.version
    replace: ${VERSION}
  - type: value
    find: paths.'/spaces/{spaceId}/features'.post.description
    replace: Create or patch features.
  - type: value
    find: paths.'/spaces/{spaceId}/tile/{type}/{tileId}'.get.description
    replace: List the features selected by tile type and tile id.
